config/routes.rb
SoundcloudQueue::Application.routes.draw do
  resources :sessions, :only => [:new] do
    get 'create', :on => :collection
  end

  resource :stream, :only => [:show], :controller => :stream

  resources :tracks, :only => [:create, :update, :destroy] do
    post 'clear', :on => :collection
  end

  root 'application#index'
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :user

  validates :track_id, :presence => true, :uniqueness => { :scope => :user_id }

  def to_param
    track_id
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :access_token, :presence => true

  has_many :tracks
end

app/models/users.rb
class Users < ActiveRecord::Base
  validates :access_token, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    redirect_to stream_url if session[SessionsController::SC_TOKEN_KEY]
  end

  private

  def authenticate
    if !session[SessionsController::SC_TOKEN_KEY]
      redirect_to new_session_url
    end
  end

  def init_user
    @user = User.where(:access_token => session[SessionsController::SC_TOKEN_KEY]).first
  end

  def init_soundcloud_from_user
    @client = Soundcloud.new(:access_token => @user.access_token)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  SC_TOKEN_KEY = "scat"

  before_filter :init_soundcloud

  def new
    redirect_to @client.authorize_url(:scope => "non-expiring")
  end

  def create
    @code = params[:code]
    @access_token = @client.exchange_token(:code => @code)
    @user = User.new
    @user.access_token = @access_token.access_token

    if @user.save
      session[SC_TOKEN_KEY] = @user.access_token
      redirect_to stream_url, :anchor => ''
    else
      render text: "Oops, Soundcloud Queue messed up."
    end
  end

  private

  def init_soundcloud
    @client = Soundcloud.new(:client_id => Rails.application.config.soundcloud_client_id,
                             :client_secret => Rails.application.config.soundcloud_client_secret,
                             :redirect_uri => sessions_url)
  end

end

app/controllers/stream_controller.rb
class StreamController < ApplicationController

  before_filter :authenticate, :init_user, :init_soundcloud_from_user

  SC_NEXT_KEY = 'next'

  def show
    @current_user = @client.get('/me')

    if params[:next]
      @stream = @client.get(params[:next])
      render :partial => "tracks", :layout => false and return
    else
      @stream = @client.get('/me/activities')
    end
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  before_filter :authenticate, :init_user
  before_filter :init_soundcloud_from_user, :only => [:update]

  def create
    @track = Track.new(track_params)
    @track.user_id = @user.id

    if @track.save
      head :ok
    else
      head :unprocessable_entity
    end
  end

  # params[:like] or params[:repost] or
  # params[:unlike] or params[:unpost] are present
  def update
    if params.has_key? :like
      @client.put("/me/favorites/#{params[:id]}")
      head :ok and return
    end

    if params.has_key? :unlike
      @client.delete("/me/favorites/#{params[:id]}")
      head :ok and return
    end

    if params.has_key? :repost
      @client.put("/me/track_reposts/#{params[:id]}")
      head :ok and return
    end

    if params.has_key? :unpost
      @client.delete("/me/track_reposts/#{params[:id]}")
      head :ok and return
    end

    head :bad_request
  end

  def destroy
    @track = @user.tracks.where(:track_id => params[:id]).first
    @track.destroy
    render :nothing => true
  end

  def clear
    @user.tracks.destroy_all
    render :nothing => true
  end

  private

  def track_params
    params.require(:track).permit(:track_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def google_analytics_tag
    return unless Rails.env == "production"

    %{<script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-47049927-1', 'morgan.io');
        ga('send', 'pageview');
      </script>}.html_safe
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stream_helper.rb
module StreamHelper
end

app/views/application/index.html.erb
<div id="connect-wrapper">
  <div id="connect">
    <h1>SoundCloud Queue</h1>
    <p>Queue up the songs you want to listen to next</p>
    <p><a href="<%= new_session_path %>">Connect</a></p>
    <p><a href="https://github.com/mhgbrown/SoundCloud-Queue">Github</a></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Soundcloud Queue</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<script src="//w.soundcloud.com/player/api.js"></script>
<%= javascript_include_tag "application" %>
<%= google_analytics_tag %>
</body>
</html>

app/views/stream/_tracks.html.erb
<% @stream.collection.each_with_index do |activity, index| %>
  <% if activity.type == "track" %>
    <li>
      <iframe data-track-id="<%= activity.origin.id %>" data-duration="<%= activity.origin.duration %>" id="track-<%= activity.origin.id %>" width="100%" src="https://w.soundcloud.com/player/?url=<%= activity.origin.uri %>&liking=false"></iframe>
      <button title="Queue" class="queue-button button<%= " active" if @user.tracks.where(:track_id => activity.origin.id).first %>">Queue</button>
      <button title="Like" class="like-button button small<%= " active" if activity.origin.user_favorite %>">Like</button>
      <button title="Repost" class="repost-button button small">Repost</button>
    </li>
  <% end %>
<% end %>
<li class="next" data-next="<%= @stream.next_href %>"></li>

app/views/stream/show.html.erb
<header id="header">
  <div class="left">
    <a href="<%= @current_user.permalink_url %>" title="<%= @current_user.username %>">
      <img src="<%= @current_user.avatar_url %>" alt="<%= @current_user.username %>">
    </a>
    <h1>SoundCloud Queue</h1>
  </div>
</header>
<%= @current_user.username %>
<div id="content">
  <div id="tracks">
    <button title="Filter by track length" id="track-length-filter" class="button">Showing All Tracks</button>
    <h2>Your Stream</h2>
    <ul>
    <%= render partial: "tracks" %>
    </ul>
  </div>
  <div id="sidebar">
    <div id="queue">
      <button title="Clear" id="clear-queue" class="button">Clear</button><h2>Next</h2>
      <ul>
        <%= render partial: "queue" %>
      </ul>
    </div>
  </div>
</div>